site/blog/2017-09-28-zegami/README.md
Migrate articles to the new website: 
-Open Power System Data
-Oleg Lavrovsky
-Matt Thompson
-Georges Labrèche
-Open Knowledge Greece
=> Migrate articles to new website

site/jobs/create-visualizations/README.md, site/jobs/do-analysis-and-machine-learning/README.md, site/jobs/do-initial-data-exploration/README.md, site/jobs/find-datasets/README.md, site/jobs/gracefully-scale-scope/README.md, site/jobs/gracefully-scale-size/README.md, site/jobs/have-a-data-hub/README.md, site/jobs/orchestrate-data-platform/README.md, site/jobs/pipeline-transformations/README.md, site/jobs/pull-dataset/README.md, site/jobs/push-dataset/README.md, site/jobs/quickly-edit-dataset/README.md, site/jobs/store-dataset/README.md, site/jobs/validate-dataset/README.md, site/jobs/version-dataset/README.md, site/products/data-package-pipelines/README.md, site/products/data-package/README.md, site/products/datahub/README.md, site/products/goodtables/README.md, site/products/labs/README.md, site/products/table-schema/README.md, site/products/tabulator/README.md
The frontmatter meta items are checked for all jobs and products page and missing items are added.
=> [frontmatter] [m] added missing tags for jobs and products page #422

contributing.md
=> [contributing][s] added contributing doc with frontmatter spec #422

package-lock.json, package.json, site/.vuepress/theme/components/Home.vue
=> [home][s]: Add typing effect to tagline

site/.vuepress/theme/components/Home.vue
Add loop effect for tagline text.
=> [home][s]- loop tagline text

site/team/index.md
=> [build][xs]- fix failing build on GitHub

site/.vuepress/theme/components/Footer.vue, site/.vuepress/theme/components/Home.vue, site/README.md, tailwind.config.js
Every section breaks nicely for smaller screen sizes now
=> implemented responsiveness to home page

cypress/integration/home_page_spec.js, package-lock.json, package.json, site/.vuepress/config.js
=> [home][s]- Add smooth scroll and back-to-top functionality

site/.vuepress/config.js, site/.vuepress/theme/components/Footer.vue, site/.vuepress/theme/components/FooterSidebar.vue
Set variables for the footer content in the config.js; 
Then replace the content of the two footers with these variables.
=> [footer][m]: Put footer content in one place

site/.vuepress/config.js, site/.vuepress/theme/components/BlogPost.vue
- automate issue creation so I don't have to create an issue when there's a new blog post.
=> [comment][xs] - automated creating issue

site/guide/README.md
Issue: https://github.com/frictionlessdata/project/issues/441
=> [guide][s] - Add Table Schema Section to the Guide

site/guide/README.md
Hey there! I hope this will be useful. If not, don't hesitate to let me know! :wink: 
- Add line 213 to require `goodtables` (this may be obvious, but maybe not to those who don't use JavaScript on a regular basis).
- Change filename on line 311 to be consistent with the rest of the tutorial.
- Fix minor issues with formatting.
=> [guide][s] - Fix Goodtables runtime error and typos

site/.vuepress/config.js, site/.vuepress/theme/components/Home.vue, tailwind.config.js
- create a group dropdown for pilot, reproducible research etc.
https://github.com/frictionlessdata/project/issues/482
=> [nav][s] - Rearrange navbar links

site/.vuepress/theme/components/BlogIndex.vue
fixes: https://github.com/frictionlessdata/project/issues/480
=> [fix][s] - fix pagination bug

site/.vuepress/config.js, site/events/README.md
fixes: https://github.com/frictionlessdata/project/issues/501
=> [event][s]: Add Frictionless Data Events Page

site/data-package/README.md
=> Fixed links in data-package page

site/blog/2020-07-10-tool-fund-intermine/README.md
adds the first 2020 tool fund grantee profile blog
=> adds Nikhil blog

site/.vuepress/config.js, site/code-of-conduct/README.md
- adds code of conduct page (https://github.com/frictionlessdata/project/issues/523)
- adds new page to the navbar under `community`
=> adds code of conduct

site/blog/2020-07-16-tool-fund-polar-institute/README.md
for the 2nd 2020 tool fund grantee profile
=> adds carles blog

site/blog/2020-08-17-frictionless-wheat/README.md
Hi @monikappv or @sglavoie could one of you please take a look at this blog & merge if OK? I'd like to publish it on Monday/Tuesday, so no rush to do it over the weekend :-)
=> adds tool fund wheat blog

site/blog/2020-08-24-august-virtual-hangout/README.md
* Contains most of the topics we have discussed as a reference for the
rest of the community.
=> [blog][m]: Update Community Hangout blog post for August

site/data-package/README.md
Discussed on Discourse 2020-09-14.
=> Change contributor from name to title as per data package specs.

site/blog/2020-10-28-october-virtual-hangout/README.md
hi @sglavoie could you please check & merge when you have a minute? thanks!
=> adds october community call blog

site/blog/2018-02-14-creating-tabular-data-packages-in-r/README.md
removes incorrect load info; fixes bad URL
=> fixes R datapackage docs

site/tooling/application/README.md
Minor text improvements to Application page
- Iterate language describing the current information on this page
- Update link to use the https url
- Remove the 'managed solution' statement because it seems to
duplicate the previous goodtables.io link
- Verified that the https link `https://try.goodtables.io/` does exists.
Let me know if this change could be accepted (or rejected) or
needs some additional changes to be approved and merged.
Thank you,
DC
=> Minor text improvements to Application page

site/blog/2021-06-01-may-virtual-hangout/README.md
Add blog for May community call.
Please preserve this line to notify @roll (lead of this repository)
=> Create May community call blog

site/README.md
Correcting DataHub heading in the 'Some of our Tooling' section (currently linking to the GoodTables page) 
Please replace this line with full information about your pull request. Make sure that tests pass before publishing it
---
=> Correct link

.github/workflows/general.yml
This should get deploys working again
---
=> deploy on push to main

site/blog/2021-06-16-new-changes-to-the-website/README.md
Publishing a blog describing changes to the website
---
=> Create a blog for changes to website

site/blog/2021-06-22-livemark/README.md
=> Adds livemark blog

site/.vuepress/enhanceApp.js
Redirecting https://frictionlessdata.io/table-schema and https://frictionlessdata.io/data-package to https://frictionlessdata.io/standards
---
=> Redirects broken links

site/blog/2021-07-12-open-data-blend/README.md
Hey @lwinfree let me know what you think.
PS Please merge image first. Thanks!
---
=> Adds open data blend blog

site/blog/2019-08-29-welcome-frictionless-fellows/README.md
Adding fellows' blog. I used the usual image, let me know if you want to change it. Thanks.
---
=> Adds fellows' blog

site/blog/2021-07-21-frictionless-repository/README.md
Adds repository blog. Please merge image first. Thanks!
---
=> Adds Repository blog

site/adoption/README.md
Fixes broken link to Pacific Northwest National Laboratory - Active Data Biology
---
=> Fixes broken link

site/blog/2021-08-09/dryad-pilot/README.md
Hey @lwinfree, can you please check that the title and subtitle are fine? Thanks!
---
=> Adds Dryad blog

site/.vuepress/config.js, site/hackathon/README.md, site/work-with-us/events/README.md
Hey @roll & @sapetti9 could you please take a look? What do you think? I added a new page (/hackathon) with general advertisement and also added a sentence to the events page that links out to the /hackathon page. Let me know if you have suggestions or please merge if you think it is OK.
Thanks!
=> adds hackathon info and page

site/blog/2021-08-16-august-12-call/README.md
I had to slightly change the title adding the day as well, since we have two calls in August
@lwinfree can you please merge the pic before? Thanks!
=> Adds community call blog

site/hackathon/README.md
=> adds hackathon project form

site/hackathon/README.md
=> adds registration forms for the hackathon

site/hackathon/README(pt-br).md
Hello. This PR adds a file README(pt-br).md in hackathon diretory. I'm an intern in OK Brazil and translated the info page to help nacional divulgation
---
=> add readme in portuguese

site/blog/2021-09-30/hackathon-preview/README.md
Hey @lwinfree can you please have a look and merge if that's OK? Especially the description, I am not 100% sure it is in very good English. :) Thanks!
As usual, merge the image first, please!
=> Adds hackathon blog

site/hackathon/README.md
=> adding times

site/adoption/README.md
Hey @lwinfree, the tool fund _Analysis of spontaneous activity patterns in developing neural circuits using Frictionless Data tools_ was not directing to the right blog, so I changed it.
=> Correcting wrong url

site/blog/2021-12-07-3rd-cohort-fellows/README.md
Hey @lwinfree (lead of this repository), can you please have a look and merge if everything is fine? Thanks!
=> Adds fellows blog

site/blog/2021-12-07-3rd-cohort-fellows/README.md
Adding a little border to the photos to make the blog easier to read. Can you check everything is fine @lwinfree (lead of this repository)?
=> Adding a border to the photos

site/blog/2021-12-17-december-community-call/README.md
Blog about December community call. Please have a look @lwinfree (lead of this repository) and merge if it looks OK!
=> Adds file for community call December

site/blog/2022-01-18-frictionless-planet/README.md
Hey @lwinfree can you please check if everything is OK and then merge? Thanks!
=> Adds frictionless planet blog

site/blog/2022-02-07-libraries-hacked/README.md
Adding the a blog/case study for libraries hacked. @lwinfree can you please have a look and merge if it's OK? Thanks!
=> Adding new blog

site/adoption/README.md
...as a case study under community projects
=> adds libraries hacked to adoption

site/people/README.md
closes https://github.com/frictionlessdata/website/issues/302
=> adds cohort 3 fellows to people page

site/adoption/README.md
closes https://github.com/frictionlessdata/project/issues/375 & closes https://github.com/frictionlessdata/website/issues/324
We can add more databases to the adoption page as we learn about them.
=> adds info on finding datasets

site/blog/2022-07-05-frictionless-planet-conversation/README.md
Reposting blog on Frictionless Planet conversation with Lacuna Fund, originally posted on the OKF blog. @lwinfree can you please review & merge? Thanks!
=> Reposting blog

site/blog/2022-07-14-flatterer/README.md
=> Adds use-case for Flatterer

site/blog/2022-08-02-community-call-july-flatterer/README.md
Hi @roll, can you please have a look at the blog and merge if it looks OK to you? Thanks!
=> Adds blog for July community call

site/blog/2022-08-29-frictionless-framework-release/README.md
Crossposting Framework v5 blog: https://framework.frictionlessdata.io/blog/2022/08-22-frictionless-framework-v5.html
=> Crossposting Framework v5 blog

site/universe/README.md
Small correction: _R-lang_ to _R_ .
=> Small correction

site/projects/README.md
Adding an hyperlink to Frictionless R.
=> Adding a hyperlink
